[theme]
base = "dark"
primaryColor = "#00e5ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2530"
textColor = "#fafafa"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
